import { IField } from '../interfaces/IField';
export const level1: IField[] = [
  {
    top: 0,
    left: 0,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 0,
    leftFieldId: null,
    rightFieldId: 1,
    topFieldId: null,
    bottomFieldId: 9,
  },
  {
    top: 0,
    left: 33.333333333333336,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 1,
    leftFieldId: 0,
    rightFieldId: 2,
    topFieldId: null,
    bottomFieldId: 10,
  },
  {
    top: 0,
    left: 66.66666666666667,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 2,
    leftFieldId: 1,
    rightFieldId: 3,
    topFieldId: null,
    bottomFieldId: 11,
  },
  {
    top: 0,
    left: 100,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 3,
    leftFieldId: 2,
    rightFieldId: 4,
    topFieldId: null,
    bottomFieldId: 12,
  },
  {
    top: 0,
    left: 133.33333333333334,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 4,
    leftFieldId: 3,
    rightFieldId: 5,
    topFieldId: null,
    bottomFieldId: 13,
  },
  {
    top: 0,
    left: 166.66666666666669,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 5,
    leftFieldId: 4,
    rightFieldId: 6,
    topFieldId: null,
    bottomFieldId: 14,
  },
  {
    top: 0,
    left: 200,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 6,
    leftFieldId: 5,
    rightFieldId: 7,
    topFieldId: null,
    bottomFieldId: 15,
  },
  {
    top: 0,
    left: 233.33333333333334,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 7,
    leftFieldId: 6,
    rightFieldId: 8,
    topFieldId: null,
    bottomFieldId: 16,
  },
  {
    top: 0,
    left: 266.6666666666667,
    topWall: true,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 8,
    leftFieldId: 7,
    rightFieldId: null,
    topFieldId: null,
    bottomFieldId: 17,
  },
  {
    top: 43,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 9,
    leftFieldId: null,
    rightFieldId: 10,
    topFieldId: 0,
    bottomFieldId: 18,
  },
  {
    top: 43,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 10,
    leftFieldId: 9,
    rightFieldId: 11,
    topFieldId: 1,
    bottomFieldId: 19,
  },
  {
    top: 43,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 11,
    leftFieldId: 10,
    rightFieldId: 12,
    topFieldId: 2,
    bottomFieldId: 20,
  },
  {
    top: 43,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 12,
    leftFieldId: 11,
    rightFieldId: 13,
    topFieldId: 3,
    bottomFieldId: 21,
  },
  {
    top: 43,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 13,
    leftFieldId: 12,
    rightFieldId: 14,
    topFieldId: 4,
    bottomFieldId: 22,
  },
  {
    top: 43,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 14,
    leftFieldId: 13,
    rightFieldId: 15,
    topFieldId: 5,
    bottomFieldId: 23,
  },
  {
    top: 43,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 15,
    leftFieldId: 14,
    rightFieldId: 16,
    topFieldId: 6,
    bottomFieldId: 24,
  },
  {
    top: 43,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 16,
    leftFieldId: 15,
    rightFieldId: 17,
    topFieldId: 7,
    bottomFieldId: 25,
  },
  {
    top: 43,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 17,
    leftFieldId: 16,
    rightFieldId: null,
    topFieldId: 8,
    bottomFieldId: 26,
  },
  {
    top: 86,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 18,
    leftFieldId: null,
    rightFieldId: 19,
    topFieldId: 9,
    bottomFieldId: 27,
  },
  {
    top: 86,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 19,
    leftFieldId: 18,
    rightFieldId: 20,
    topFieldId: 10,
    bottomFieldId: 28,
  },
  {
    top: 86,
    left: 66.66666666666667,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 20,
    leftFieldId: 19,
    rightFieldId: 21,
    topFieldId: 11,
    bottomFieldId: 29,
  },
  {
    top: 86,
    left: 100,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 21,
    leftFieldId: 20,
    rightFieldId: 22,
    topFieldId: 12,
    bottomFieldId: 30,
  },
  {
    top: 86,
    left: 133.33333333333334,
    topWall: true,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 22,
    leftFieldId: 21,
    rightFieldId: 23,
    topFieldId: 13,
    bottomFieldId: 31,
  },
  {
    top: 86,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 23,
    leftFieldId: 22,
    rightFieldId: 24,
    topFieldId: 14,
    bottomFieldId: 32,
  },
  {
    top: 86,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 24,
    leftFieldId: 23,
    rightFieldId: 25,
    topFieldId: 15,
    bottomFieldId: 33,
  },
  {
    top: 86,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 25,
    leftFieldId: 24,
    rightFieldId: 26,
    topFieldId: 16,
    bottomFieldId: 34,
  },
  {
    top: 86,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 26,
    leftFieldId: 25,
    rightFieldId: null,
    topFieldId: 17,
    bottomFieldId: 35,
  },
  {
    top: 129,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 27,
    leftFieldId: null,
    rightFieldId: 28,
    topFieldId: 18,
    bottomFieldId: 36,
  },
  {
    top: 129,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 28,
    leftFieldId: 27,
    rightFieldId: 29,
    topFieldId: 19,
    bottomFieldId: 37,
  },
  {
    top: 129,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 29,
    leftFieldId: 28,
    rightFieldId: 30,
    topFieldId: 20,
    bottomFieldId: 38,
  },
  {
    top: 129,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 30,
    leftFieldId: 29,
    rightFieldId: 31,
    topFieldId: 21,
    bottomFieldId: 39,
  },
  {
    top: 129,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 31,
    leftFieldId: 30,
    rightFieldId: 32,
    topFieldId: 22,
    bottomFieldId: 40,
  },
  {
    top: 129,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 32,
    leftFieldId: 31,
    rightFieldId: 33,
    topFieldId: 23,
    bottomFieldId: 41,
  },
  {
    top: 129,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 33,
    leftFieldId: 32,
    rightFieldId: 34,
    topFieldId: 24,
    bottomFieldId: 42,
  },
  {
    top: 129,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 34,
    leftFieldId: 33,
    rightFieldId: 35,
    topFieldId: 25,
    bottomFieldId: 43,
  },
  {
    top: 129,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 35,
    leftFieldId: 34,
    rightFieldId: null,
    topFieldId: 26,
    bottomFieldId: 44,
  },
  {
    top: 172,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 36,
    leftFieldId: null,
    rightFieldId: 37,
    topFieldId: 27,
    bottomFieldId: 45,
  },
  {
    top: 172,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 37,
    leftFieldId: 36,
    rightFieldId: 38,
    topFieldId: 28,
    bottomFieldId: 46,
  },
  {
    top: 172,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 38,
    leftFieldId: 37,
    rightFieldId: 39,
    topFieldId: 29,
    bottomFieldId: 47,
  },
  {
    top: 172,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 39,
    leftFieldId: 38,
    rightFieldId: 40,
    topFieldId: 30,
    bottomFieldId: 48,
  },
  {
    top: 172,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 40,
    leftFieldId: 39,
    rightFieldId: 41,
    topFieldId: 31,
    bottomFieldId: 49,
  },
  {
    top: 172,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 41,
    leftFieldId: 40,
    rightFieldId: 42,
    topFieldId: 32,
    bottomFieldId: 50,
  },
  {
    top: 172,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 42,
    leftFieldId: 41,
    rightFieldId: 43,
    topFieldId: 33,
    bottomFieldId: 51,
  },
  {
    top: 172,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 43,
    leftFieldId: 42,
    rightFieldId: 44,
    topFieldId: 34,
    bottomFieldId: 52,
  },
  {
    top: 172,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 44,
    leftFieldId: 43,
    rightFieldId: null,
    topFieldId: 35,
    bottomFieldId: 53,
  },
  {
    top: 215,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 45,
    leftFieldId: null,
    rightFieldId: 46,
    topFieldId: 36,
    bottomFieldId: 54,
  },
  {
    top: 215,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 46,
    leftFieldId: 45,
    rightFieldId: 47,
    topFieldId: 37,
    bottomFieldId: 55,
  },
  {
    top: 215,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 47,
    leftFieldId: 46,
    rightFieldId: 48,
    topFieldId: 38,
    bottomFieldId: 56,
  },
  {
    top: 215,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 48,
    leftFieldId: 47,
    rightFieldId: 49,
    topFieldId: 39,
    bottomFieldId: 57,
  },
  {
    top: 215,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 49,
    leftFieldId: 48,
    rightFieldId: 50,
    topFieldId: 40,
    bottomFieldId: 58,
  },
  {
    top: 215,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 50,
    leftFieldId: 49,
    rightFieldId: 51,
    topFieldId: 41,
    bottomFieldId: 59,
  },
  {
    top: 215,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 51,
    leftFieldId: 50,
    rightFieldId: 52,
    topFieldId: 42,
    bottomFieldId: 60,
  },
  {
    top: 215,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 52,
    leftFieldId: 51,
    rightFieldId: 53,
    topFieldId: 43,
    bottomFieldId: 61,
  },
  {
    top: 215,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 53,
    leftFieldId: 52,
    rightFieldId: null,
    topFieldId: 44,
    bottomFieldId: 62,
  },
  {
    top: 258,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 54,
    leftFieldId: null,
    rightFieldId: 55,
    topFieldId: 45,
    bottomFieldId: 63,
  },
  {
    top: 258,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 55,
    leftFieldId: 54,
    rightFieldId: 56,
    topFieldId: 46,
    bottomFieldId: 64,
  },
  {
    top: 258,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 56,
    leftFieldId: 55,
    rightFieldId: 57,
    topFieldId: 47,
    bottomFieldId: 65,
  },
  {
    top: 258,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 57,
    leftFieldId: 56,
    rightFieldId: 58,
    topFieldId: 48,
    bottomFieldId: 66,
  },
  {
    top: 258,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 58,
    leftFieldId: 57,
    rightFieldId: 59,
    topFieldId: 49,
    bottomFieldId: 67,
  },
  {
    top: 258,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 59,
    leftFieldId: 58,
    rightFieldId: 60,
    topFieldId: 50,
    bottomFieldId: 68,
  },
  {
    top: 258,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 60,
    leftFieldId: 59,
    rightFieldId: 61,
    topFieldId: 51,
    bottomFieldId: 69,
  },
  {
    top: 258,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 61,
    leftFieldId: 60,
    rightFieldId: 62,
    topFieldId: 52,
    bottomFieldId: 70,
  },
  {
    top: 258,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 62,
    leftFieldId: 61,
    rightFieldId: null,
    topFieldId: 53,
    bottomFieldId: 71,
  },
  {
    top: 301,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 63,
    leftFieldId: null,
    rightFieldId: 64,
    topFieldId: 54,
    bottomFieldId: 72,
  },
  {
    top: 301,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 64,
    leftFieldId: 63,
    rightFieldId: 65,
    topFieldId: 55,
    bottomFieldId: 73,
  },
  {
    top: 301,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 65,
    leftFieldId: 64,
    rightFieldId: 66,
    topFieldId: 56,
    bottomFieldId: 74,
  },
  {
    top: 301,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 66,
    leftFieldId: 65,
    rightFieldId: 67,
    topFieldId: 57,
    bottomFieldId: 75,
  },
  {
    top: 301,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 67,
    leftFieldId: 66,
    rightFieldId: 68,
    topFieldId: 58,
    bottomFieldId: 76,
  },
  {
    top: 301,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 68,
    leftFieldId: 67,
    rightFieldId: 69,
    topFieldId: 59,
    bottomFieldId: 77,
  },
  {
    top: 301,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 69,
    leftFieldId: 68,
    rightFieldId: 70,
    topFieldId: 60,
    bottomFieldId: 78,
  },
  {
    top: 301,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 70,
    leftFieldId: 69,
    rightFieldId: 71,
    topFieldId: 61,
    bottomFieldId: 79,
  },
  {
    top: 301,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 71,
    leftFieldId: 70,
    rightFieldId: null,
    topFieldId: 62,
    bottomFieldId: 80,
  },
  {
    top: 344,
    left: 0,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 72,
    leftFieldId: null,
    rightFieldId: 73,
    topFieldId: 63,
    bottomFieldId: 81,
  },
  {
    top: 344,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 73,
    leftFieldId: 72,
    rightFieldId: 74,
    topFieldId: 64,
    bottomFieldId: 82,
  },
  {
    top: 344,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 74,
    leftFieldId: 73,
    rightFieldId: 75,
    topFieldId: 65,
    bottomFieldId: 83,
  },
  {
    top: 344,
    left: 100,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 75,
    leftFieldId: 74,
    rightFieldId: 76,
    topFieldId: 66,
    bottomFieldId: 84,
  },
  {
    top: 344,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 76,
    leftFieldId: 75,
    rightFieldId: 77,
    topFieldId: 67,
    bottomFieldId: 85,
  },
  {
    top: 344,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 77,
    leftFieldId: 76,
    rightFieldId: 78,
    topFieldId: 68,
    bottomFieldId: 86,
  },
  {
    top: 344,
    left: 200,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 78,
    leftFieldId: 77,
    rightFieldId: 79,
    topFieldId: 69,
    bottomFieldId: 87,
  },
  {
    top: 344,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: false,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 79,
    leftFieldId: 78,
    rightFieldId: 80,
    topFieldId: 70,
    bottomFieldId: 88,
  },
  {
    top: 344,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: false,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 80,
    leftFieldId: 79,
    rightFieldId: null,
    topFieldId: 71,
    bottomFieldId: 89,
  },
  {
    top: 387,
    left: 0,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: true,
    hasHole: false,
    hasDiamond: false,
    fieldId: 81,
    leftFieldId: null,
    rightFieldId: 82,
    topFieldId: 72,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 33.333333333333336,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 82,
    leftFieldId: 81,
    rightFieldId: 83,
    topFieldId: 73,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 66.66666666666667,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 83,
    leftFieldId: 82,
    rightFieldId: 84,
    topFieldId: 74,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 100,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 84,
    leftFieldId: 83,
    rightFieldId: 85,
    topFieldId: 75,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 133.33333333333334,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 85,
    leftFieldId: 84,
    rightFieldId: 86,
    topFieldId: 76,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 166.66666666666669,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 86,
    leftFieldId: 85,
    rightFieldId: 87,
    topFieldId: 77,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 200,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 87,
    leftFieldId: 86,
    rightFieldId: 88,
    topFieldId: 78,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 233.33333333333334,
    topWall: false,
    bottomWall: true,
    rightWall: false,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 88,
    leftFieldId: 87,
    rightFieldId: 89,
    topFieldId: 79,
    bottomFieldId: null,
  },
  {
    top: 387,
    left: 266.6666666666667,
    topWall: false,
    bottomWall: true,
    rightWall: true,
    leftWall: false,
    hasHole: false,
    hasDiamond: false,
    fieldId: 89,
    leftFieldId: 88,
    rightFieldId: null,
    topFieldId: 80,
    bottomFieldId: null,
  },
];
