export const SET_ALL_FIELDS = 'SET_ALL_FIELDS';
export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';
export const REMOVE_DIAMOND_FROM_FIELD = 'REMOVE_DIAMOND_FROM_FIELD';
export const SET_SCORE = 'SET_SCORE';
export const SET_PAUSE_MENU_STATE = 'SET_PAUSE_MENU_STATE';
export const UPDATE_FIELD = 'UPDATE_FIELD';
